[package]
name = "modelshelf-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }
fs2 = "0.4"
url = "2"
same-file = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[dev-dependencies]
tempfile.workspace = true
